// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkelhqgxdpadlwochvoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZWxocWd4ZHBhZGx3b2Nodm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTE5MjksImV4cCI6MjA2NTU4NzkyOX0.E6mbUcNbl4sRVZped4hFY4eyJwJpxRmtzOI-6cublPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);